from typing import Dict, Any
from .llm_client import ClaudeClient

CRITIC_SYSTEM_PROMPT = """You are a senior Wealth Management Auditor. 
Your job is to critically review the advice given by another advisor.
You will be provided with:
1. The raw portfolio data
2. The advice generated by the primary advisor

Review the advice for:
1. Mathematical accuracy (did they misinterpret the crash percentages?)
2. Actionability (is the advice specific or vague?)
3. Verdict accuracy (does the Aggressive/Balanced/Conservative label match the math?)

Provide a 3-4 sentence critique. Do not rewrite the advice, just critique it."""

def critique_explanation(client: ClaudeClient, portfolio: Dict[str, Any], explanation: Dict[str, Any]) -> str:
    """
    Uses the LLM to critique its own previous output (Bonus feature).
    """
    import json
    
    user_message = (
        f"--- PORTFOLIO DATA ---\n{json.dumps(portfolio, indent=2)}\n\n"
        f"--- ADVISOR OUTPUT ---\n{json.dumps(explanation, indent=2)}\n\n"
        "Please provide your critique."
    )
    
    return client.generate_response(
        system_prompt=CRITIC_SYSTEM_PROMPT,
        user_message=user_message,
        max_tokens=400
    )
